# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

development:
  adapter: postgresql
  encoding: unicode
  database: rails_blog_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: rails_blog_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    timeout: 5000
  cache:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["PGUSER"] || "postgres" %>
    password: <%= ENV["PGPASSWORD"] || "" %>
    host: <%= ENV["PGHOST"] || "localhost" %>
    port: <%= ENV["PGPORT"] || 5432 %>
    timeout: 5000
    migrations_paths: db/cache_migrate
  queue:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["PGUSER"] || "postgres" %>
    password: <%= ENV["PGPASSWORD"] || "" %>
    host: <%= ENV["PGHOST"] || "localhost" %>
    port: <%= ENV["PGPORT"] || 5432 %>
    timeout: 5000
    migrations_paths: db/queue_migrate
  cable:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["PGUSER"] || "postgres" %>
    password: <%= ENV["PGPASSWORD"] || "" %>
    host: <%= ENV["PGHOST"] || "localhost" %>
    port: <%= ENV["PGPORT"] || 5432 %>
    timeout: 5000
    migrations_paths: db/cable_migrate
